---
- name: add rpm key for elastic.co
  rpm_key:
    key: "{{ filebeat_gpg_url }}"

- name: create beats yum repo
  yumrepo:
    name: beats
    baseurl: "{{ filebeat_repo_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ filebeat_gpg_url }}"

- name: install beats
  yum: name={{ item }} state=present 
  with_items: 
    - filebeat
    - topbeat
    - packetbeat
  
- name: create filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify:
    - restart filebeat

- name: create topbeat.yml
  template:
    src: topbeat.yml.j2
    dest: /etc/topbeat/topbeat.yml
  notify:
    - restart topbeat

- name: create packetbeat.yml
  template:
    src: packetbeat.yml.j2
    dest: /etc/packetbeat/packetbeat.yml
  notify:
    - restart packetbeat

- name: flush handlers to prevent start then restart
  meta: flush_handlers

- name: start and enable filebeat
  service: name="{{ item }}" state=started enabled=true
  with_items:
    - filebeat
    - topbeat
    - packetbeat
